### ISSUE TITLE
[refact] community

### ISSUE THREAD

**Issue by jjjjjinseo** [comprehensive-design/style_scanner_frontend#121]
### Community 
- [x] 커뮤니티 글쓰기 css 수정 및 훅 분리 , PR #133 
- [x] 커뮤니티 홈 css 수정 및 훅 분리
- [x] 커뮤니티 컴포넌트 css 수정 , PR #137 
- [x] 커뮤니티 댓글 창 css 수정 및 훅 분리 
PR #138 
#139 
#140 
 - [x] 변경된 api 연결 , PR #150 
 - [x] pagination , PR #160
