### ISSUE TITLE
[ API ] 홈 - 피드

### ISSUE THREAD

**Issue by jjjjjinseo** [comprehensive-design/style_scanner_frontend#99]
## 📑 TASK
- [x] axios GET으로, 사용자가 팔로우 한 인플루언서의 피드를 모두 모아볼 수 있게 합니다.
- [ ] 버튼을 누르면 POST로 백엔드에 전달합니다.
- [x] Item창에 사용자가 선택한 피드 정보를 전달합니다. 

## ❔Question

HomeFeed에서 피드를 누르면, 피드 정보를 HomeItem으로 이동하게 했고, 거기서 또 ComunityWrite 버튼을 누르면, 또 피드 정보를 전달해서 잘 구현했는데, 굳이 백엔드에 전달해야하나요??
